services:
  server:
    build:
      context: .
      dockerfile: dockerfile
    container_name: Friday-Discord-Bot
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  